apiVersion: apps/v1
kind: Deployment
metadata:
  name: myapp-deployment
  labels:
    tier: frontend
    app: nginx
spec:
  selector:
    matchLabels:
      tier: myapp
  template:
    metadata:
      name: nginx-2
      labels:
        tier: myapp
    spec:
      containers:
        - name: nginx
          image: nginx
  replicas: 6